### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by robwise**
- Adds `eslint` for style consistency, use via `npm run lint` or `npm run lint:fix`
- Implements ES6
- Greatly enhances startup time via lazy-loading
- General logic refactoring
- Adds in-app error messages

## New Error Messages
error
filetype warning

## Startup Time Before
timecop before

## Startup Time After
timecop after

### CODE REVIEW

**Comment by robwise** [comment]
This collides with https://github.com/jlongster/prettier-atom/pull/14, but that PR is erroring so I couldn't merge it ahead of this, and this one would supersede those changes.

**Comment by jlongster** [comment]
Wow, this all looks awesome. Thanks a lot for all this work! I'm going to merge this, close #14, and push an update because I need to update it to prettier 0.0.7 anyways.

**Comment by jlongster** [comment]
> Adds eslint for style consistency

Oh the irony :)

**Comment by jlongster** [comment]
I see you updated it to 0.0.7, thanks! Just published to the registry.

**Comment by robwise** [comment]
> Oh the irony :)

lol, I'm a belt and suspenders kind of guy ¯\_(ツ)_/¯

**Pull request merged**
