### PR TITLE
Expose all core prettier options in Atom config

### LINKED ISSUE #4: Configuration?
How does one specify options?

### PR DESCRIPTION
**Pull request by schnerd**
Exposes the [core prettier api options](https://github.com/jlongster/prettier#api) as configuration options in the Atom package.

image

Fixes #4

### CODE REVIEW

**Comment by 1st8** [comment]
Just tried it, works great! 👍

**Comment by oviava** [comment]
up for this, also - the bracket spacing option won't work unless the PR for bumping up to 0.0.4 https://github.com/jlongster/prettier-atom/pull/12 is also added (variable name changes for the bracket spacing option https://github.com/jlongster/prettier/pull/70 )

**Comment by jlongster** [comment]
Awesome, thanks a lot!

**Comment by ferittuncer** [comment]
I can't find these options for some reason. `0.56.4`

**Comment by robwise** [comment]
These options no longer exist, Prettier changed to using a config file so now that's the way prettier-atom works as well. See https://prettier.io/docs/en/configuration.html

**Pull request merged**
